### ISSUE TITLE
DPL-679-1 - Check if endpoint should be deprecated

### ISSUE THREAD

**Issue by emrojo** [sanger/event_warehouse#18] opened 2020-01-14 10:06 UTC
The consumers leave some endpoints available to create events from an hypothetical http server. We should check if this is needed still.

**Comment by JamesGlover** [comment] 2020-08-14 12:13
Where do you mean? 

Develop does have the beginnings of a http server which was intended for an API, but I don't *think* this has any create actions enabled. (This probably needs to be revisited. I went back to it shortly before paternity leave and some of the gems we were going to use have been abandoned) Is there another server somewhere?

**Comment by BenTopping** [comment] 2023-12-07 12:16
Closing as in Done.

**Closed by BenTopping** 2023-12-07 12:16 UTC
Labels: Technical Debt
